Fixes #721 [dbsnapshot] Allow Azure and other cloud-based server sources with port number.
codesmithtools/Templates pull request #722
Opened 2023-06-09 13:10 UTC by cyberjetx

The issue wasn't permissions exactly. It was the inability to create a directory from the server name/ server source when it's name is like tcp:myCloudData.database.windows.net,5588.  So I have added a rudimentary check in the ParseServerName function to look for a colon.  

With the example above I choose **myCloudData** as the parsed server name.  I also check for a blank name and if it is I select the computer name as a last resort otherwise we would create a hidden folder eg .MyDatabaseName 

I hope this is clear and I am open to input and suggestion.

2023-06-09 13:10 UTC, CLAassistant commented
[![CLA assistant check](https://cla-assistant.io/pull/badge/not_signed)](https://cla-assistant.io/codesmithtools/Templates?pullRequest=722) <br/>Thank you for your submission! We really appreciate it. Like many open source projects, we ask that you sign our [Contributor License Agreement](https://cla-assistant.io/codesmithtools/Templates?pullRequest=722) before we can accept your contribution.<br/><hr/>**Joe Johnston** seems not to be a GitHub user. You need a GitHub account to be able to sign the CLA. If you have already a GitHub account, please [add the email address used for this commit to your account](https://help.github.com/articles/why-are-my-commits-linked-to-the-wrong-user/#commits-are-not-linked-to-any-user).<br/><sub>You have signed the CLA already but the status is still pending? Let us [recheck](https://cla-assistant.io/check/codesmithtools/Templates?pullRequest=722) it.</sub>

2023-06-19 11:55 UTC, niemyjski requested changes

2023-06-19 11:55 UTC, niemyjski commented on Templates/Database/DbSnapshot/DbSnapshot.cst
> +
I cleaned up the trimming of the server name and noticed clean name on the second part wasn't being applied. Can you please try my suggestions.

```suggestion

    string name = _serverName.Trim();
    if (name.StartsWith(".") || name.StartsWith("(local)") || name.StartsWith("127.0.0.1")) {
        _serverName = CleanName(System.Windows.Forms.SystemInformation.ComputerName);
    } else if (name.Contains(":")) {
        // Allow a cloud source with port  TCP:xxx,1111 or a UDP:xxxx,1433 eg tcp:myCloudData.database.windows.net,5588
        _serverName = CleanName(Regex.Replace(name, @"^.*\:(\w+)(\..*$)", "$1", RegexOptions.IgnoreCase)); 
    }

    if (String.IsNullOrEmpty(_serverName.Trim())) {
        _serverName = CleanName(System.Windows.Forms.SystemInformation.ComputerName); 
    }

```

2023-06-19 11:55 UTC, niemyjski commented
Thanks for your PR, I've left some comments above.

2023-06-19 11:56 UTC, niemyjski commented
Fixes https://github.com/codesmithtools/Templates/issues/721

2023-06-19 13:40 UTC, cyberjetx commented
Changes understood and committed.

2023-06-20 13:09 UTC, niemyjski approved these changes

2023-06-20 13:10 UTC, merged

2023-06-20 13:18 UTC, niemyjski commented
Thanks for your PR!